# Generated by Django 2.2.5 on 2019-09-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
