# Generated by Django 2.2.5 on 2019-09-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
