# Generated by Django 2.2.5 on 2019-09-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_auto_20190917_1843'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('codigo', 'codigo_barra')},
        ),
    ]
